/*
 * Q‑SCI LLM Evaluator
 *
 * This module replaces the lightweight heuristic evaluator with an
 * evaluation powered by OpenAI's GPT model.  It sends the paper
 * content to the OpenAI Chat Completion API along with a carefully
 * constructed prompt and expects the model to return a JSON
 * structure describing the quality of the paper.  The output is
 * identical in shape to the original evaluator: a quality score
 * (0–100), a traffic light (🟢/🟡/🔴), and arrays of positive and
 * negative aspects with supporting source text snippets.  To use
 * this evaluator, you must provide your own OpenAI API key.
 */

// Define a fallback evaluator early.  If this script fails to initialize due
// to a syntax error (e.g. mis‑formatted API key), the popup will still
// find a qsciEvaluatePaper function and report a meaningful error rather
// than "qsciEvaluatePaper is not a function".  The fallback
// returns a rejected promise with an error.
(function() {
  const fallbackError = function() {
    return Promise.reject(new Error('Q‑SCI LLM evaluator is not initialized. Please ensure the extension has loaded correctly and that your OpenAI API key is set via the extension settings.'));
  };
  
  if (typeof window !== 'undefined' && typeof window.qsciEvaluatePaper === 'undefined') {
    window.qsciEvaluatePaper = fallbackError;
  }
  if (typeof self !== 'undefined' && typeof self.qsciEvaluatePaper === 'undefined') {
    self.qsciEvaluatePaper = fallbackError;
  }
})();

(() => {
  // ---------------------------------------------------------------------------
  // Configuration
  //
  // The OpenAI API key will be retrieved from chrome.storage at
  // runtime.  Do not edit this file to insert your key; instead set
  // your API key via the extension's settings page.  See
  // options.html/options.js for details.
  let OPENAI_API_KEY = null;

  // Model to use.  You can adjust this if you have access to
  // different models (e.g. 'gpt-4-turbo', 'gpt-3.5-turbo-0125').
  const MODEL_NAME = 'gpt-4o-mini';
  
  // Export MODEL_NAME for use in chat functionality
  if (typeof window !== 'undefined') {
    window.QSCI_MODEL_NAME = MODEL_NAME;
  }

  // Temperature setting for the model.  Lower values make the output
  // more deterministic.
  const TEMPERATURE = 0.0;
  
  // Top-p sampling for faster token generation without quality loss
  // 0.9 provides good balance between speed and quality
  const TOP_P = 0.9;

  // API endpoint for OpenAI chat completions
  const OPENAI_API_ENDPOINT = 'https://api.openai.com/v1/chat/completions';

  // Timeout for API requests (in milliseconds)
  // Increased to 120 seconds to handle longer PDF extractions and complex analyses
  // This allows sufficient time for PDF processing and complex papers like The Lancet
  const API_TIMEOUT_MS = 120000; // 120 seconds (2 minutes)

  // Maximum text length to send to the API (in characters)
  // Optimized to balance analysis quality with response time (<20 seconds)
  // ~15,000 chars = ~3,750 tokens, which provides sufficient context while
  // keeping API processing time under target
  const MAX_TEXT_LENGTH = 15000;

  // Maximum length for a line to be considered a section header
  // Longer lines are likely paragraph text, not headers
  const MAX_SECTION_HEADER_LENGTH = 100;

  // Minimum proportion of text that should be extracted by section detection
  // If less than this proportion is extracted, fall back to simple truncation
  const SECTION_EXTRACTION_THRESHOLD = 0.5;

  /**
   * Intelligently truncate text to fit within token limits while preserving
   * the most important sections for quality analysis.
   * 
   * Priority and allocation:
   * - Methods: 100% (NEVER truncated - crucial for quality assessment)
   * - Abstract: 35% (Important study summary)
   * - Results: 10% (Beginning of results section)
   * - Discussion: 5% (Only limitations and advantages paragraphs)
   * - Introduction: Last paragraph only (where hypotheses are typically stated)
   * 
   * @param {string} text - The full paper text
   * @returns {string} Truncated text optimized for analysis
   */
  function truncateTextIntelligently(text) {
    if (!text || text.length <= MAX_TEXT_LENGTH) {
      return text;
    }

    console.log(`Q‑SCI LLM Evaluator: Text length ${text.length} exceeds limit, applying intelligent truncation...`);

    // Section markers to identify key parts (case-insensitive)
    // Patterns are designed to match section headers, not inline text
    // They require word boundaries and typically short lines to avoid false positives
    const sectionPatterns = {
      abstract: /^\s*(abstract|summary)\s*$/i,
      methods: /^\s*(methods?|methodology|materials? and methods?|study design|participants?|procedures?)\s*$/i,
      results: /^\s*(results?|findings?|outcomes?)\s*$/i,
      discussion: /^\s*(discussion|conclusion|conclusions?|interpretation)\s*$/i,
      introduction: /^\s*(introduction|background)\s*$/i
    };

    // Try to extract sections by finding section headers
    const lines = text.split('\n');
    const sections = {
      abstract: [],
      methods: [],
      results: [],
      discussion: [],
      introduction: [],
      other: []
    };
    
    let currentSection = 'other';
    
    for (const line of lines) {
      const trimmedLine = line.trim();
      
      // Check if this line is a section header
      let foundSection = false;
      for (const [sectionName, pattern] of Object.entries(sectionPatterns)) {
        if (pattern.test(trimmedLine) && trimmedLine.length < MAX_SECTION_HEADER_LENGTH) {
          // Short lines matching section patterns are likely headers
          currentSection = sectionName;
          foundSection = true;
          break;
        }
      }
      
      if (!foundSection && trimmedLine.length > 0) {
        sections[currentSection].push(line);
      }
    }

    // Build truncated text by prioritizing sections
    // Updated allocation strategy based on quality analysis importance:
    // - Methods: 100% (CRUCIAL - never truncate, most important for quality)
    // - Abstract: 35% (Important summary of the study)
    // - Results: 10% (Less important for quality analysis)
    // - Discussion: 5% (Only limitations/advantages paragraphs)
    // - Introduction: Last paragraph only (hypotheses location)
    
    let truncatedText = '';
    
    // 1. Abstract - important summary (35% = 5,250 chars)
    if (sections.abstract.length > 0) {
      const sectionText = sections.abstract.join('\n');
      const allocation = Math.floor(MAX_TEXT_LENGTH * 0.35);
      const label = 'Abstract';
      
      if (sectionText.length > allocation) {
        truncatedText += `\n[${label}]\n${sectionText.substring(0, allocation)}...\n`;
      } else {
        truncatedText += `\n[${label}]\n${sectionText}\n`;
      }
    }
    
    // 2. Methods - CRITICAL, include 100% without truncation
    // This is the most important section for quality analysis
    if (sections.methods.length > 0) {
      const sectionText = sections.methods.join('\n');
      truncatedText += `\n[Methods]\n${sectionText}\n`;
    }
    
    // 3. Results - reduced importance (10% = 1,500 chars)
    if (sections.results.length > 0) {
      const sectionText = sections.results.join('\n');
      const allocation = Math.floor(MAX_TEXT_LENGTH * 0.10);
      const label = 'Results';
      
      if (sectionText.length > allocation) {
        truncatedText += `\n[${label}]\n${sectionText.substring(0, allocation)}...\n`;
      } else {
        truncatedText += `\n[${label}]\n${sectionText}\n`;
      }
    }
    
    // 4. Discussion - only limitations and advantages (5% = 750 chars)
    // Focus on the most relevant parts for quality assessment
    if (sections.discussion.length > 0) {
      const sectionText = sections.discussion.join('\n');
      const allocation = Math.floor(MAX_TEXT_LENGTH * 0.05);
      
      // Try to extract paragraphs mentioning limitations or advantages
      const paragraphs = sectionText.split(/\n\s*\n/);
      let discussionText = '';
      const limitationKeywords = /\b(limitation|drawback|weakness|constraint|disadvantage|caveat)\b/i;
      const advantageKeywords = /\b(advantage|strength|benefit|robust|reliable|novel|innovative)\b/i;
      
      for (const para of paragraphs) {
        if (limitationKeywords.test(para) || advantageKeywords.test(para)) {
          discussionText += para + '\n\n';
          if (discussionText.length > allocation) break;
        }
      }
      
      // If we didn't find specific paragraphs, take beginning
      if (discussionText.trim().length === 0) {
        discussionText = sectionText.substring(0, allocation);
      }
      
      truncatedText += `\n[Discussion]\n${discussionText.substring(0, allocation)}...\n`;
    }
    
    // 5. Introduction - only last paragraph (where hypotheses are usually mentioned)
    if (sections.introduction.length > 0) {
      const sectionText = sections.introduction.join('\n');
      const paragraphs = sectionText.split(/\n\s*\n/).filter(p => p.trim().length > 0);
      
      if (paragraphs.length > 0) {
        // Take the last paragraph (usually contains hypotheses)
        const lastParagraph = paragraphs[paragraphs.length - 1];
        truncatedText += `\n[Introduction - Hypotheses]\n${lastParagraph}\n`;
      }
    }

    // If we still have room and collected "other" content, add some of it
    if (truncatedText.length < MAX_TEXT_LENGTH && sections.other.length > 0) {
      const remainingSpace = MAX_TEXT_LENGTH - truncatedText.length;
      const otherText = sections.other.join('\n');
      if (otherText.length > remainingSpace) {
        truncatedText += '\n[Additional Content]\n' + otherText.substring(0, remainingSpace) + '...';
      } else {
        truncatedText += '\n[Additional Content]\n' + otherText;
      }
    }

    // Fallback: if section extraction didn't work well (very short result), 
    // just take the beginning of the text
    if (truncatedText.length < MAX_TEXT_LENGTH * SECTION_EXTRACTION_THRESHOLD) {
      console.log('Q‑SCI LLM Evaluator: Section extraction yielded limited content, using simple truncation');
      // Reserve space for the truncation message to ensure we don't exceed MAX_TEXT_LENGTH
      const truncationMessage = '\n[... content truncated for length ...]';
      const reservedLength = MAX_TEXT_LENGTH - truncationMessage.length;
      truncatedText = text.substring(0, reservedLength) + truncationMessage;
    }

    console.log(`Q‑SCI LLM Evaluator: Text truncated from ${text.length} to ${truncatedText.length} characters`);
    return truncatedText;
  }

  /**
   * Build the prompt for the OpenAI model.  The system message
   * instructs the model to behave as a scientific paper quality
   * evaluator and to respond with JSON in a specific format.  The
   * user message includes the title, source URL and the paper text to
   * be evaluated.
   *
   * @param {string} title - Paper title
   * @param {string} sourceUrl - URL of the paper
   * @param {string} text - Paper text content
   * @param {string} language - Language code ('de' or 'en') for output
   * @returns {Array} messages suitable for OpenAI chat completion API
   */
  function buildMessages(title, sourceUrl, text, language = 'de') {
    // Apply intelligent truncation to keep analysis time under 20 seconds
    const truncatedText = truncateTextIntelligently(text);
    const wasTruncated = text.length > MAX_TEXT_LENGTH;
    
    // Determine language for output
    const languageName = language === 'de' ? 'German' : 'English';
    const languageNative = language === 'de' ? 'Deutsch' : 'English';
    
    // Build system prompt - only mention truncation if it actually occurred
    let systemPrompt = `You are Q‑SCI, an expert scientific publication quality evaluator.\n\n` +
      `IMPORTANT: You MUST respond in ${languageName} (${languageNative}). All text fields including 'reasoning', 'aspect', 'explanation', and all other text content must be in ${languageName}.\n\n` +
      `When given the text of a scientific publication, you must assess the overall quality of the study using standard evidence‑grading principles. `;
    
    if (wasTruncated) {
      systemPrompt += `Note: This paper's text was intelligently truncated to include the most relevant sections (Abstract, Methods, Results, Discussion) to optimize processing time. `;
    }
    
    systemPrompt += `Focus on the actual paper content only — ignore the reference list and citations. ` +
      `Identify study design features (e.g. randomized controlled trial, crossover, meta‑analysis, observational study), sample size and clear reporting practices. ` +
      `Consider whether the study is blinded, placebo controlled or non‑inferiority, whether it follows reporting guidelines (e.g. CONSORT for trials, PRISMA for reviews, STROBE for observational studies), and whether sample sizes are adequate. ` +
      `Assign a quality score between 0 and 100. 90–100 = 🟢 Green, 70–89 = 🟡 Amber, below 70 = 🔴 Red. ` +
      `\n\n` +
      `ASPECT COUNT REQUIREMENTS - Adjust the number of aspects based on the quality score:\n` +
      `- For scores ≥85%: Provide at least 6 positive aspects and 3-4 negative aspects\n` +
      `- For scores 70-84%: Provide 4-5 positive aspects and 4-5 negative aspects\n` +
      `- For scores 50-69%: Provide 3-4 positive aspects and 5-6 negative aspects\n` +
      `- For scores <50%: Provide at least 3 positive aspects and at least 6 negative aspects\n` +
      `- Always provide at least 3 aspects in each category (positive and negative)\n` +
      `- Total aspects should be between 6 and 12 combined\n` +
      `\n` +
      `Each aspect must be directly supported by a snippet of source text taken verbatim from the paper. ` +
      `For each aspect, set the 'aspect' field to a complete, clear sentence that stands alone and communicates the evaluation point in plain language (e.g., "The study objective is stated clearly" or "The sample size is small"). ` +
      `CRITICAL REQUIREMENT FOR SOURCE_TEXT: You MUST copy the exact text word-for-word from the paper content provided below. This is a CITATION that will be shown to users in quotation marks. DO NOT write any new text, DO NOT paraphrase, DO NOT summarize, and DO NOT generate explanatory text. Simply copy and paste the relevant sentence(s) from the paper that support each aspect. The 'source_text' must be a verbatim substring that appears exactly as written in the provided paper content. If an aspect is based on reasoning regarding multiple parts of the publication where no single exact citation can be extracted, set 'source_text' to an empty string (""). Every non-empty 'source_text' value will be displayed as a direct quotation from the paper. ` +
      `EXPLANATION REQUIREMENT: For each aspect (positive and negative), you must also provide an 'explanation' field that explains in 2-3 sentences why this aspect is significant for the quality assessment. This explanation helps users understand the importance and implications of each finding. ` +
      `Do not invent content: every source text snippet must be present in the provided paper text. ` +
      `Ignore the reference list entirely when choosing aspects and source text. ` +
      `REASONING REQUIREMENT: Provide a 'reasoning' field with 2-3 paragraphs (NOT sentences - paragraphs with 3-5 sentences each) that thoroughly explains why you assigned this specific quality score. Include: (1) an overview of the study's strengths, (2) a discussion of its weaknesses or limitations, and (3) a concluding statement on the overall quality assessment. This reasoning should be comprehensive and detailed. ` +
      `JOURNAL INFORMATION: If you can identify the journal name from the provided source URL or paper content, research and provide the journal's impact factor. Include this in a 'journal_info' object with keys 'journal_name' (string) and 'impact_factor' (string, if available, otherwise "Not available"). If you cannot determine the journal, omit this field. ` +
      `\n\n` +
      `REMEMBER: ALL text in your response must be in ${languageName} (${languageNative}).\n\n` +
      `Return your answer strictly as a JSON object with the following keys:\n\n` +
      `quality_percentage (number),\n` +
      `traffic_light (string, one of \"🟢 Green\", \"🟡 Amber\", \"🔴 Red\"),\n` +
      `reasoning (string in ${languageName}, 2-3 paragraphs explaining the quality score in detail),\n` +
      `positive_aspects (array of objects with keys 'aspect' (in ${languageName}), 'source_text', and 'explanation' (in ${languageName})),\n` +
      `negative_aspects (array of objects with keys 'aspect' (in ${languageName}), 'source_text', and 'explanation' (in ${languageName})),\n` +
      `journal_info (optional object with keys 'journal_name' and 'impact_factor')\n\n` +
      `Do not include any code block formatting, backticks or additional commentary.  Only output a single valid JSON object.`;

    const user = `Paper Title: ${title || 'Unknown Title'}\n` +
      `Source URL: ${sourceUrl || 'N/A'}\n\n` +
      `Paper Content:\n${truncatedText || ''}`;

    return [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: user }
    ];
  }

  /**
   * Parse the response from OpenAI.  The API returns a JSON object
   * with choices, each containing a message.  This function
   * extracts the content, attempts to parse it as JSON, and returns
   * the resulting object.  It also normalizes the structure to
   * ensure compatibility with the extension.
   *
   * @param {any} responseJson - Parsed JSON response from API
   * @returns {any} Parsed evaluation object
   */
  function parseOpenAIResponse(responseJson) {
    try {
      const content = responseJson?.choices?.[0]?.message?.content || '';
      // Attempt to parse the content directly as JSON
      let parsed;
      try {
        parsed = JSON.parse(content.trim());
      } catch (inner) {
        // Remove common formatting markers like triple backticks or "json:" prefix
        const cleaned = content
          .replace(/^\s*```json\s*/i, '')
          .replace(/^\s*```\s*/i, '')
          .replace(/```\s*$/i, '')
          .trim();
        parsed = JSON.parse(cleaned);
      }
      // Ensure required keys exist and types are correct
      if (!parsed || typeof parsed !== 'object') throw new Error('Invalid JSON structure');
      const quality = typeof parsed.quality_percentage === 'number' ? parsed.quality_percentage : 0;
      const traffic = typeof parsed.traffic_light === 'string' ? parsed.traffic_light : '🟡 Amber';
      const reasoning = typeof parsed.reasoning === 'string' ? parsed.reasoning : '';
      const pos = Array.isArray(parsed.positive_aspects) ? parsed.positive_aspects : [];
      const neg = Array.isArray(parsed.negative_aspects) ? parsed.negative_aspects : [];
      return { 
        quality_percentage: quality, 
        traffic_light: traffic, 
        reasoning: reasoning,
        positive_aspects: pos, 
        negative_aspects: neg 
      };
    } catch (e) {
      console.error('Q‑SCI LLM Evaluator: Failed to parse OpenAI response', e);
      return null;
    }
  }

  /**
   * Evaluate a paper using OpenAI's chat completion API.  This function
   * builds the prompt, sends the request to OpenAI, parses the
   * response, and returns the evaluation.  If the API key is not
   * provided or an error occurs, the function will throw an error.
   *
   * @param {string} text - The paper text to evaluate
   * @param {string} title - The paper title
   * @param {string} sourceUrl - The URL of the paper
   * @returns {Promise<any>} A promise that resolves to the evaluation object
   */
  async function evaluate(text, title, sourceUrl) {
    console.log('Q‑SCI LLM Evaluator: Starting evaluation...');
    console.log('Q‑SCI LLM Evaluator: Input text length:', text?.length || 0, 'characters');
    
    if (!text || text.trim().length < 50) {
      throw new Error('Insufficient text provided for analysis');
    }

    // Get current language from i18n service
    // Use self for service worker context, window for browser context
    const globalContext = typeof window !== 'undefined' ? window : self;
    let currentLanguage = 'de'; // Default to German
    if (globalContext.QSCIi18n && typeof globalContext.QSCIi18n.getLanguage === 'function') {
      currentLanguage = globalContext.QSCIi18n.getLanguage();
      console.log('Q‑SCI LLM Evaluator: Using language:', currentLanguage);
    } else {
      console.log('Q‑SCI LLM Evaluator: i18n service not available, using default language:', currentLanguage);
    }

    // Fetch the OpenAI API key from the backend instead of local storage
    // This ensures the key is managed centrally and users don't need to manually enter it
    let apiKey;
    try {
      console.log('Q‑SCI LLM Evaluator: Fetching API key from backend...');
      console.log('Q‑SCI LLM Evaluator: QSCIAuth available:', typeof globalContext.QSCIAuth !== 'undefined');
      console.log('Q‑SCI LLM Evaluator: getOpenAIApiKey function available:', typeof globalContext.QSCIAuth?.getOpenAIApiKey === 'function');
      
      // Check if QSCIAuth is available (it should be loaded before this script)
      if (typeof globalContext.QSCIAuth === 'undefined' || typeof globalContext.QSCIAuth.getOpenAIApiKey !== 'function') {
        const errorMsg = 'Authentication module not available. Please ensure you are logged in and the extension is properly loaded. Try reloading the extension at chrome://extensions/';
        console.error('Q‑SCI LLM Evaluator:', errorMsg);
        throw new Error(errorMsg);
      }
      
      console.log('Q‑SCI LLM Evaluator: Calling getOpenAIApiKey()...');
      apiKey = await globalContext.QSCIAuth.getOpenAIApiKey();
      
      if (!apiKey) {
        const errorMsg = 'Failed to retrieve API key from backend. The backend may not be properly configured. Please ensure the /api/extension-auth endpoint is deployed and the OPENAI_API_KEY environment variable is set.';
        console.error('Q‑SCI LLM Evaluator:', errorMsg);
        throw new Error(errorMsg);
      }
      
      console.log('Q‑SCI LLM Evaluator: API key fetched successfully (length:', apiKey.length, ')');
    } catch (error) {
      console.error('Q‑SCI LLM Evaluator: Error fetching API key:', error);
      console.error('Q‑SCI LLM Evaluator: Error stack:', error.stack);
      console.error('Q‑SCI LLM Evaluator: Error type:', error.constructor.name);
      
      // Provide more specific error messages based on the error type
      let userFriendlyMessage = error.message;
      
      // If the error already contains helpful information, use it
      if (error.message.includes('404') || error.message.includes('endpoint not found')) {
        userFriendlyMessage = 'Backend endpoint not found. The /api/extension-auth endpoint needs to be deployed. Please check your backend configuration.';
      } else if (error.message.includes('500') || error.message.includes('server error')) {
        userFriendlyMessage = 'Backend server error. The OPENAI_API_KEY environment variable may not be set. Please check your backend configuration.';
      } else if (error.message.includes('401') || error.message.includes('Unauthorized')) {
        userFriendlyMessage = 'Authentication failed. Your session may have expired. Please logout and login again.';
      } else if (error.message.includes('Failed to fetch') || error.message.includes('NetworkError') || error.message.includes('Unable to connect')) {
        userFriendlyMessage = 'Unable to connect to backend server. Please check your internet connection and ensure the backend at https://www.q-sci.org is accessible.';
      }
      
      throw new Error(userFriendlyMessage);
    }

    const messages = buildMessages(title, sourceUrl, text, currentLanguage);
    const body = JSON.stringify({
      model: MODEL_NAME,
      messages: messages,
      temperature: TEMPERATURE,
      top_p: TOP_P,
      // Force JSON response format for faster parsing and more reliable output
      response_format: { type: "json_object" },
      // Provide a max_tokens to cap the response length. Increased to 1500 tokens
      // to accommodate longer reasoning (2-3 paragraphs), explanations for each aspect,
      // and journal information.
      max_tokens: 1500
    });

    const headers = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    };

    // Perform the API request using fetch with a timeout to prevent hanging
    // The fetch API is available in the Chrome extension context.
    // Host permissions for https://api.openai.com/* must be declared in manifest.json.
    console.log('Q‑SCI LLM Evaluator: Sending request to OpenAI API...');
    
    // Create an AbortController for timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      controller.abort();
      console.error(`Q‑SCI LLM Evaluator: Request timed out after ${API_TIMEOUT_MS / 1000} seconds`);
    }, API_TIMEOUT_MS);

    try {
      const response = await fetch(OPENAI_API_ENDPOINT, {
        method: 'POST',
        headers: headers,
        body: body,
        signal: controller.signal
      });

      clearTimeout(timeoutId);
      console.log('Q‑SCI LLM Evaluator: OpenAI API response received, status:', response.status);

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Q‑SCI LLM Evaluator: OpenAI API error:', response.status, errorText);
        throw new Error(`OpenAI API request failed: ${response.status} ${response.statusText}\n${errorText}`);
      }
      
      const json = await response.json();
      console.log('Q‑SCI LLM Evaluator: Response parsed successfully');
      
      const parsed = parseOpenAIResponse(json);
      if (!parsed) {
        throw new Error('Failed to parse evaluation from OpenAI response');
      }
      
      console.log('Q‑SCI LLM Evaluator: Evaluation completed successfully');
      return parsed;
    } catch (error) {
      clearTimeout(timeoutId);
      
      // Handle abort/timeout errors
      if (error.name === 'AbortError') {
        throw new Error(`Request to OpenAI API timed out after ${API_TIMEOUT_MS / 1000} seconds. The API may be experiencing issues. Please try again later.`);
      }
      
      // Handle network errors with more robust checking
      if (error?.message?.includes('Failed to fetch') || error?.message?.includes('NetworkError')) {
        throw new Error('Unable to connect to OpenAI API. Please check your internet connection and try again.');
      }
      
      throw error;
    }
  }

  // Expose the evaluator on the window object for popup context
  // and on self for service worker context
  // The popup script or background worker will call qsciEvaluatePaper()
  // Note that this function returns a promise, so the caller must handle asynchronous evaluation.
  if (typeof window !== 'undefined') {
    window.qsciEvaluatePaper = evaluate;
  }
  if (typeof self !== 'undefined') {
    self.qsciEvaluatePaper = evaluate;
  }
})();